sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - soure $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
    # The following three commands you have to put in the Google cloud shell as well
  - gcloud config set project gentle-epoch-228613
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials wollikub
    # Until here
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password_stdin
  - docker build -t tux1980/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tux1980/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master